### ISSUE TITLE
Reach out to Goncalo’s team for more TOPMed sample data/metadata and VCFs

### ISSUE THREAD

**Issue by briandoconnor** [DataBiosphere/team-lighthouse-point#36]
* more data beyond Phase 1
* VCF files for Phase 1 and beyond
* Contact Jonathan and have a followup with him

Michael, I'm assigning you for now, reassign as needed.

**Comment by mikebaumann** [comment]
This may be unnecessary as during the DCC data stewards preview webinar on 4/2, it was announced that the TOPMed data would be made available in cloud buckets in early April.

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

[~mbaumann] I'm assigning to myself temporarily to decorate this ticket with info from Goncalo about accessing the full 100K in Google... I think we need to pursue this in parallel with official access.

**Comment by cricketsloan** [comment]
➤ Brian O&#39;Connor commented:

I sent this today... I think it's important to try to get direct bucket access since I don't trust that we'll be able to leverage signed URLs via the "Sequence Data Delivery Pilot":

Hey Jonathon and Albert,

I had a good conversation with Albert and Goncalo at the Commons F2F meeting on 20180427 in Bethesda.  Specifically, the plan to make more data available in the requester pays bucket in about a month or so.  My understanding was that you all would push the ~100K CRAMs and VCFs to the google bucket once you have the latest version of the variant calling done.

Since it's been about a month or so I just wanted to check in with you all, is that process on track?

We got the presentation by NCBI/MITRE on the “Sequence Data Delivery Pilot” tooling.  Which Team Calcium is definitely going to play around with.  But my concern is that signed URLs are currently a bit problematic for use in FireCloud.  We're currently using direct google paths for the time being in our development and I suspect this will be a requirement for our work in the pilot phase given how quickly the September deadline is coming up.  It would be great if we could get access to the expanded TOPMed CRAMs/VCFs in the mean time. So we can deliver on the functionality of providing access to this data for a set of data producers to run workflows on the CRAMs in the pilot phase.  Per Goncalo's use case that he's provided to us and others in Data Commons/Data STAGE.

Thanks for the update!  We really appreciate everything you all are doing for us on data access and workflows!

Brian

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

It has been made clear that from here on out we need to go through official channels
